- name: retrieving OVH linux kernel headers
  unarchive:
    src: ftp://ftp.ovh.net/made-in-ovh/bzImage/4.14.12/ovhkernel-4.14.12-xxxx-std-ipv6-64.tgz
    dest: /usr/src/
    remote_src: yes

- name: add deps to build kernel
  apt:
    name: "{{item}}"
  with_items:
    - libelf-dev
    - make
    - gcc
    - libncurses5-dev
    - lzma
    - dpkg-dev
    - wget

# previously adapted from ftp://ftp.ovh.net/made-in-ovh/bzImage/4.14.12/config-4.14.12-xxxx-std-ipv6-64
# mainly added CONFIG_MODULES=y and launched make to generate a new .config file
- name: copy custom kernel config
  copy:
    src: .config
    dest: /usr/src/ovhkernel-4.14.12-xxxx-std-ipv6-64/.config

- name: recompile OVH kernel
  shell: make deb-pkg --jobs 10
  args:
    chdir: /usr/src/ovhkernel-4.14.12-xxxx-std-ipv6-64/
    creates: /usr/src/linux-image-4.14.12-oslandia_4.14.12-oslandia-2_amd64.deb
  async: 1200
  poll: 10

- name: install custom kernel
  apt:
    deb: "{{item}}"
  with_items:
    - /usr/src/linux-image-4.14.12-oslandia_4.14.12-oslandia-2_amd64.deb
    - /usr/src/linux-headers-4.14.12-oslandia_4.14.12-oslandia-2_amd64.deb
