- name: Get info about installed vms
  command: VBoxManage list vms
  register: vm_list
  failed_when: no
  changed_when: no

- name: Ensure the ova is present
  stat: path="{{ win_ova }}"
  register: install_ova_present

- fail:
    msg: This installation script expect you to put the windows 10 installation .ova in {{ win_ova }} on the guest machine (you can modify this path via the win_ova variable)
  when: not install_ova_present.stat.exists

# TODO: add test to ensure the OVA has guest additions installed

- name: Import the Windows OVA
  command: vboxmanage import {{ win_ova }} --vsys 0 --vmname win10 --ostype Windows10_64 --memory {{ win_memory }}
  when: (vm_list.stdout | regex_search('"win10"')) == None  

- name: Take snapshot
  command: VBoxManage snapshot win10 take "win10_installed"
  when: (vm_infos.stdout | regex_search('SnapshotName.*="win10_installed"')) == None
