# Trigger variable PACKAGE_NAME
package:
  stage: build
  script:
      - cmd /s /c "cd ${PACKAGE_NAME} && package.cmd ${DELIVERY_ENV}"
  only:
      - triggers
  tags:
      - win10

package_tempus:
  stage: build
  script:
      - ./build_tempus.sh
  tags:
      - win10
      - oslandia
  when: manual
