# Trigger variable PACKAGE_NAME
package:
  stage: build
  script:
      - cd packages/${PACKAGE_NAME}
      - if [ -x package.sh ]; then /bin/bash ./package.sh ${DELIVERY_ENV}; else cmd /c "package.cmd ${DELIVERY_ENV}"; fi
      - cd ../..
      - scp scripts/genini scripts/gen_setup_ini.sh ci@hekla.oslandia.net:~/
      - ssh ci@hekla.oslandia.net ./gen_setup_ini.sh ${DELIVERY_ENV}
  only:
      - triggers
  tags:
      - win10
      - osgeo4w
