- name: Check ansible setup on windows
  command: vboxmanage guestproperty get win10 ansible_setup
  register: ansible_setup
  changed_when: no
  become: yes

- name: Copy ansible authorization script to virtualbox host
  template: src=win_ansible_setup.ps1 dest={{ virtualbox_base_folder }}/win_ansible_setup.ps1
  when: "(ansible_setup.stdout | regex_search('Value: done')) == None"
  become: yes

- name: Copy ansible authorization script from virtualbox host to windows guest
  command: vboxmanage guestcontrol win10 copyto --username {{ win_username }} --password {{ win_password }} --target-directory 'c:/Users/{{ win_username }}/Documents/win_ansible_setup.ps1' {{ virtualbox_base_folder }}/win_ansible_setup.ps1
  when: "(ansible_setup.stdout | regex_search('Value: done')) == None"
  become: yes

- name: Authorize script execution
  command: >
    vboxmanage guestcontrol win10 run --username {{ win_username }} --password {{ win_password }} --exe "c:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" --
    -Command "Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Bypass -Force"
  when: "(ansible_setup.stdout | regex_search('Value: done')) == None"
  become: yes

- name: Execute ansible authorization script
  command: >
    VBoxManage --nologo guestcontrol win10 run --username {{ win_username }} --password {{ win_password }}  --exe "c:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" --
    -Command "Start-Process powershell -ArgumentList '-file c:/Users/{{ win_username }}/Documents/win_ansible_setup.ps1' -Verb runas -Wait"
  when: "(ansible_setup.stdout | regex_search('Value: done')) == None"
  become: yes

- name: Mark ansible setup as done on vm
  command: vboxmanage guestproperty set win10 ansible_setup done
  when: "(ansible_setup.stdout | regex_search('Value: done')) == None"
  become: yes

