- name: Get info about win10 vm
  command: VBoxManage showvminfo --machinereadable win10
  register: vm_infos
  failed_when: no
  changed_when: no

- name: Create win10 vm
  command: VBoxManage createvm --name win10 --ostype Windows10_64 --register --basefolder {{ virtualbox_base_folder }}
  when: vm_infos.rc != 0

- name: Configure win10 vm memory
  command: VBoxManage modifyvm win10 --memory {{ win_memory }}
  when: (vm_infos.stdout | regex_search('memory=' + win_memory | string)) == None

- name: Create a virtual disk for vm
  command: VBoxManage createmedium --filename {{ virtualbox_base_folder }}/win10/win10.vdi --size {{ win_disk_size | default('60000') }} --format VDI
  args:
    creates: "{{ virtualbox_base_folder }}/win10/win10.vdi"

- name: Create a controller for attaching the disk
  command: VBoxManage storagectl win10 --name "SATA Controller" --add sata --controller IntelAHCI
  when: (vm_infos.stdout | regex_search('storagecontrollername\d="SATA Controller"')) == None

- name: Attach the disk to the vm
  command: VBoxManage storageattach win10 --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium {{ virtualbox_base_folder }}/win10/win10.vdi
  when: (vm_infos.stdout | regex_search('"SATA Controller-\d-\d"="' + virtualbox_base_folder + '.*vdi"')) == None

- name: Ensure the iso is present
  stat: path="{{ win_iso }}"
  register: install_iso_present

- fail:
    msg: This installation script expect you to put the windows 10 installation .iso in {{ win_iso }} on the guest machine (you can modify this path via the win_iso variable)
  when: not install_iso_present.stat.exists

- name: Create the IDE controller
  command: VBoxManage storagectl win10 --name "IDE Controller" --add ide --controller PIIX4
  when: (vm_infos.stdout | regex_search('storagecontrollername\d="IDE Controller"')) == None

- name: Attach the installation iso
  command: VBoxManage storageattach win10 --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium {{ win_iso }}
  when: (vm_infos.stdout | regex_search('"IDE Controller-\d-\d"="' + win_iso + '"')) == None

# On Ubuntu 16.04 with this version of virtualbox, the path for UnattendetTemplates is wrong apparently
- name: Ensure virtualbox has the needed unattended install configuration
  file:
    src: /usr/lib/virtualbox/UnattendedTemplates
    dest: /usr/share/virtualbox/UnattendedTemplates
    state: link

- name: Install or start vm
  command: >
    VBoxManage unattended install win10
    --start-vm=headless
    --iso={{ win_iso }}
    --user={{ win_username }}  --password={{ win_password }}
    --install-additions --additions-iso={{virtualbox_base_folder}}/VBoxGuestAdditions_5.2.6.iso
    --time-zone=UTC
    {{ '--image-index=' + win_image_index if win_image_index is defined else '' }}
    --image-index=8
    {{ '--key=' + win_key if win_key is defined else '' }}
  register: install_vm_result
  failed_when: "install_vm_result.rc != 0 and not (install_vm_result.stderr | regex_search('Machine .* is currently running'))"
  changed_when: "install_vm_result.rc == 0"

- name: Take snapshot
  command: VBoxManage snapshot win10 take "win10_installed"
  when: (vm_infos.stdout | regex_search('SnapshotName.*="win10_installed"')) == None

