- name: Get info about registered runners
  command: gitlab-runner list
  register: runners
  failed_when: no
  changed_when: no
  become: yes

- name: Register the runner
  command: >
    gitlab-runner register --non-interactive
      --name win10_{{ runner_host_name | default(ansible_hostname) }}
      --url {{ gitlab_url }}
      --registration-token {{ runner_registration_token }}
      --tag-list osgeo4w,win10,{{ runner_host_name | default(ansible_hostname) }}
      --virtualbox-base-name win10
      --executor virtualbox
      --ssh-user {{ win_username }}
      --ssh-identity-file /home/gitlab-runner/.ssh/id_rsa
      --virtualbox-base-snapshot win10_ready4ci
  when: ( runners.stderr | regex_search('win10_' + (runner_host_name | default(ansible_hostname)))) == None
  become: yes

