- name: Create local user for the vm to scp to
  user:
    name: windows
    comment: "Windows build VM"
  become: yes

- name: Add www-data to this user group, to be able to read its file
  user:
    name: www-data
    groups: windows
  become: yes

- name: Create folder that will be served by nginx, while making it writable by windows
  file: path=/usr/share/nginx/html/osgeo4w state=directory group=windows mode=0770
  become: yes

- name: get windows ssh key
  slurp:
    src: "{{cygwin_path}}\\home\\{{ansible_user}}\\.ssh\\id_rsa.pub"
  register: win_pub_key
  delegate_to: localhost

- name: Add windows key to authorized key
  authorized_key:
    user: windows
    key: "{{ win_pub_key['content'] | b64decode }}"
  become: yes

# this is in rigor incorrect because open to MITM attack. For this instance (vm to host), I believe it is safe
- name: Make sure known_host is populated in vm
  win_command: "{{ cygwin_path }}/bin/ssh -o StrictHostKeyChecking=no windows@10.0.2.2 'echo ok'"
  delegate_to: localhost

- name: Get info about win10 vm
  command: VBoxManage showvminfo --machinereadable win10
  register: vm_infos
  failed_when: no
  changed_when: no
  become: yes

- name: Take snapshot
  command: VBoxManage snapshot win10 take "win10_ready4ci"
  when: (vm_infos.stdout | regex_search('SnapshotName.*="win10_ready4ci"')) == None
  become: yes

- debug:
    msg: "variable fetch {{ fetch_osgeo4w_mirror }} {{ fetch_osgeo4w_mirror | bool }}"

- name: Fetch a local mirror of the OSGeo4W repository
  command: >
    rsync -av {{ osgeo4w_rsync }} /usr/share/nginx/html/osgeo4w
  become: yes
  become_user: windows
  when: fetch_osgeo4w_mirror | bool
