- name: install linux headers
  apt:
    name: "linux-headers-{{ansible_kernel}}"
  when: inventory_hostname != "esg.oslandia.net"

- name: ensure virtualbox repo key is present
  apt_key:
    url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    state: present

- name: add virtualbox repository
  apt_repository:
    repo: "deb https://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib"
    state: present

- name: installing virtualbox
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - dkms
    - virtualbox-5.2
    - xserver-xorg

- name: adding virtualbox base folder directory
  file:
    name: "{{virtualbox_base_folder}}"
    state: directory

- name: get virtualbox extension pack
  get_url:
    url: https://download.virtualbox.org/virtualbox/5.2.6/Oracle_VM_VirtualBox_Extension_Pack-5.2.6-120293.vbox-extpack
    dest: "{{virtualbox_base_folder}}/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack"
  register: extpack

- name: List installed extpacks
  command: vboxmanage list extpacks
  register: list_extpacks
  changed_when: no

- name: install virtualbox extension pack
  shell: "VBoxManage extpack install {{virtualbox_base_folder}}/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack --accept-license=56be48f923303c8cababb0bb4c478284b688ed23f16d775d729b89a2e8e5f9eb"
  when: extpack.changed or (list_extpacks.stdout | regex_search('Extension Packs[:]{1} 0')) != None

- name: download virtualbox guest additions iso
  get_url:
    url: https://download.virtualbox.org/virtualbox/5.2.6/VBoxGuestAdditions_5.2.6.iso
    dest: "{{virtualbox_base_folder}}/VBoxGuestAdditions_5.2.6.iso"
