- name: Set windows proxy
  win_shell: " {{ item }}"
  with_items:
    - Set-ItemProperty -path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings" ProxyEnable -value 1
    - Set-ItemProperty -path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings" -name ProxyServer -value {{ http_proxy }}
  when: not ((http_proxy is undefined) or (http_proxy is none) or (http_proxy | trim == ''))

- name: Set windows ACS
  win_shell: Set-ItemProperty -path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings" AutoConfigURL -value {{ win_acs }}
  when: not((win_acs is undefined) or (win_acs is none) or (win_acs | trim == ''))

- name: copy configuration file for Visual Studio installation
  win_copy:
    src: files/AdminDeployment.xml
    dest: C:/Users/{{ ansible_user }}/Downloads/
    
- name: install Visual Studio 2015 Community update 3 with VC++
  win_chocolatey:
    name: visualstudio2015community
    params: '"--AdminFile C:/Users/{{ ansible_user }}/Downloads/AdminDeployment.xml"'
    timeout: 10000
  when: (install_msvc | bool)

- name: install Visual Studio 2015 Professional update 3 with VC++
  win_chocolatey:
    name: visualstudio2015professional
    params: '"--AdminFile C:/Users/{{ ansible_user }}/Downloads/AdminDeployment.xml"'
    tiöeout: 10000
  when: (install_msvc_pro | bool)

- name: install dependency walker
  win_chocolatey:
    name: dependencywalker
    state: latest

- name: install wget
  win_chocolatey:
    name: wget
    state: latest

- name: install cmake 3.7.2
  win_chocolatey:
    name: cmake
    version: '3.7.2'

- name: download OSGeo4W
  win_get_url:
    url: http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe
    dest: C:/Users/{{ ansible_user }}/Downloads
    timeout: 60
    force: no

- name: install dependencies from OSGeo4W
  win_command: C:/Users/{{ ansible_user }}/Downloads/osgeo4w-setup-x86_64.exe -g -q -A -R C:\OSGeo4W64 -a x86_64 -k -O -s http://osgeo4w-oslandia.com/mirror -P setup -P shell -P setuptools -p "{{ (http_proxy | urlsplit('netloc')) if http_proxy is defined else ""  }}"

- name: install cygwin
  win_chocolatey:
    name: cygwin
    params: '"/InstallDir:{{cygwin_path}}"'

- name: create home directory
  win_file: path="{{cygwin_path}}\\home\\{{ansible_user}}" state=directory

- name: make sure home permissions are ok
  win_command: "{{cygwin_path}}/bin/chown.exe -R {{ cygwin_user_with_domain | default(ansible_user)}} /home/{{ansible_user}}"

# https://docs.gitlab.com/runner/executors/virtualbox.html#checklist-for-windows-vms
- name: install cyg-get utility
  win_chocolatey:
    name: cyg-get
    state: latest

- name: install gitlab-runner dependencies
  win_command: C:/ProgramData/chocolatey/bin/cyg-get.bat sshd git

- name: install some build dependencies
  win_command: C:/ProgramData/chocolatey/bin/cyg-get.bat tar patch flex bison ssh wget

- name: install cygwin shortcut
  win_shortcut:
    src: "{{ cygwin_path}}/Cygwin.bat"
    dest: "C:/Users/{{ ansible_user}}/Desktop/Cygwin.lnk"
    icon: "{{ cygwin_path }}/cygwin.ico"

- name: download git-lfs
  win_get_url:
    url: https://github.com/git-lfs/git-lfs/releases/download/v2.4.0/git-lfs-windows-2.4.0.exe
    dest: "C:/Users/{{ ansible_user }}/Downloads"

- name: install git-lfs
  win_package:
    path: "C:/Users/{{ ansible_user }}/Downloads/git-lfs-windows-2.4.0.exe"
    product_id: '{286391DE-F778-44EA-9375-1B21AAA04FF0}'
    arguments: /silent

- name: install Notepad++
  win_chocolatey:
    name: notepadplusplus
    state: latest

- name: install unzip
  win_chocolatey:
    name: unzip
    state: latest

- name: install 7zip
  win_chocolatey:
    name: 7zip
    state: latest

- name: create .ssh directory
  win_file: path="{{cygwin_path}}\\home\\{{ansible_user}}\\.ssh" state=directory

- name: generate ssh key
  win_command: "{{cygwin_path}}\\bin\\ssh-keygen.exe -P '' -f {{cygwin_path}}\\home\\{{ansible_user}}\\.ssh\\id_rsa"
  args:
    creates: "{{cygwin_path}}\\home\\{{ansible_user}}\\.ssh\\id_rsa"

# ssh-keygen on windows created them with 755 permissions for me
- name: Fix private key permissions
  win_command: "{{cygwin_path}}\\bin\\bash -c \"/bin/chmod.exe 0700 /home/{{ansible_user}}/.ssh/id_rsa\""
